services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lh-assist-backend
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      CHATBOT_FASTAPI_BASE_URL: ${CHATBOT_FASTAPI_BASE_URL}
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: lh-assist-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: lh-assist-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    restart: unless-stopped