services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lh-assist-backend
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      CHATBOT_FASTAPI_BASE_URL: ${CHATBOT_FASTAPI_BASE_URL}
    restart: unless-stopped