spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    jdbc:
      initialize-schema: never

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  cors:
    allowed-origins:
      - "https://d1v7ka3ykr3zod.cloudfront.net"
      - "https://lh-assist.cloud"

logging:
  level:
    org.apache.fontbox.ttf.CmapSubtable: ERROR
    org.apache.pdfbox.pdmodel.font.PDType1Font: ERROR